### Establishing SQL connecting in R

install.packages("RMySQL")
library(RMySQL)

con <- dbConnect(MySQL(),
                 user = "root",
                 pwd = "*****",
                 dbname="RBaseball",
                 host = "127.0.0.1",
                 port=3306)
#NOTE: password has been starred out

#Downloading and extracting data from .zip folder
load.gamelog <- function(period, season){
  download.file(url = paste("https://www.retrosheet.org/gamelogs/gl", period,".zip", sep=""),
                destfile = paste("gl",period,".zip",sep="")
  )
  
  unzip(paste("gl",period,".zip",sep=""))
  setwd('/Users/faizanaviwala/Downloads')
  seasons <- c(list.files(path= paste("gl",period,sep="")))
  
  gamelog <- read.table(paste("GL",season,".TXT",sep=""),
                        sep=",",stringsAsFactors = F)
  file.remove(paste("gl",period,".zip",sep=""))
  file.remove(paste("GL",season,".TXT",sep=""))
  gamelog
}


gl2019 <- load.gamelog('2010_19',2019)
#Woohoo! it works!

head(gl2019)
#we see that the column names are randomly generated by R and therefore not meaninful.
#We can assign meaninful names like so:

glheaders <- read.csv("https://raw.githubusercontent.com/maxtoki/baseball_R/master/data/game_log_header.csv")
names(gl2019) <- names(glheaders) 
head(gl2019)

#Now, we want to transfer these data in a table into the Database that we've created
dbWriteTable(con, name="gamelogs", value=gl2019, append=TRUE, row.names=F)
#Should return TRUE
#We can check that this was successful by refreshing the database on our localhost



#Appending additional records onto the existing table in our database
appendGameLogs <- function(start=2017, end=2017,period,headersFile="https://raw.githubusercontent.com/maxtoki/baseball_R/master/data/game_log_header.csv",
                           dbTableName="gamelogs"){
  require(RMySQL)
  conn <- dbConnect(MySQL(),
                   user = "root",
                   pwd = "faiza7860",
                   dbname="RBaseball",
                   host = "127.0.0.1",
                   port=3306)
  glheaders <- read.csv("https://raw.githubusercontent.com/maxtoki/baseball_R/master/data/game_log_header.csv")
  for (season in start:end){
    print(paste(Sys.time(),"working on season:", season))
    flush.console()
    gamelogs <- load.gamelog(period,season)
    head(gamelogs)
    glheaders <- read.csv(headersFile)
    names(gamelogs) <- names(glheaders)
    #gamelogs$GAME_ID <- paste(gamelogs$HomeTeam, gamelogs$Date, gamelogs$DoubleHeader, sep="")
    #gamelogs$YEAR_ID <- substr(gamelogs$Date,1, 4)
    dbWriteTable(conn,name=dbTableName,value = gamelogs, append=TRUE,row.names=FALSE)
    
  }
  
 
}


appendGameLogs(start=2017, end=2017, period='2010_19',
               headersFile = "https://raw.githubusercontent.com/maxtoki/baseball_R/master/data/game_log_header.csv", 
               dbTableName="gamelogs")
#Woohoo! It works!






### Querying Data from R ###
con
NLAttendance <- dbGetQuery(con, "select date, hometeam, dayofweek, attendence
                            from gamelogs
                            where date > 20170403
                            and hometeam in ('MIA','PIT')")




NLAttendance$attendence <- ifelse(NLAttendance$attendence==0,NA,NLAttendance$attendence)

NLAttendance$dayofweek <- factor(NLAttendance$dayofweek, levels = c("Sat","Sun","Mon","Tues",
                                                                    "Wed","Thurs","Fri"))
avgatt <- aggregate(attendence~hometeam + dayofweek, data=NLAttendance, FUN=mean)
#what did this do? find the average attendence by day of week for each team


library(lattice)
xyplot(attendence ~ dayofweek, data=avgatt,
       groups = hometeam,
       pch=c("MIA","PIT"), cex=2, col="black",
       xlab="day of the week",
       ylab="attnedence"
)


#What does this show us? For each dat of the week, average attendence is higher for PIT than MIA.

#transforming this into ggplot format:
library(ggplot2)

ggplot(avgatt) +
  geom_point(aes(y=attendence,x=dayofweek,col=hometeam)) + ggtitle("Avg Attendance by Day of Week: MIA vs. PIT")
                                                                      


#Coors Field:
con <- dbConnect(MySQL(),
                 user = "root",
                 pwd = "faiza7860",
                 dbname="RBaseball",
                 host = "127.0.0.1",
                 port=3306)
rockies.game <- dbGetQuery(con, "select Date, parkID, visitingteam, hometeam, VisitorRunsScored as AWR, HomeRunsScore as HRS
                    from gamelogs
                    where (hometeam='COL' or visitingteam='COL')
                    and DATE>20170402")


head(rockies.game)

rockies.game$runs <- rockies.game$AWR + rockies.game$HRS 
table(rockies.game$parkID)
#coors park id is in retrosheet is DEN02
rockies.game$coors <- rockies.game$parkID=='DEN02'

#visualization to compare the offensive output by the Rockies and their opponents at Coors (home field) and other ballparks
ggplot(aes(x=substr(Date,1, 4), y=runs, col=coors), data=rockies.game) + 
  stat_summary(fun.data="mean_cl_boot") + xlab("season") + 
  ylab("runs per game (combined for both teams") + 
  scale_color_discrete(name="location", labels=c("other field", "Coors (home) field"))+
  ggtitle("Evaluating Rockies' performance at Home field vs. Other fields")


#So we can see that their performance for each of these three seasons was better at the home field
#Follow up question: Is this true for all or most teams? 
#Perhaps we can determine this by evaulating a random sample of teams

### Boxplot Answering the same Q:

ggplot(aes(x=substr(Date,1, 4), y=runs, col=coors), data=rockies.game) +
  geom_boxplot() + scale_color_discrete(name="location", labels=c("other field", "Coors (home) field"))+
  ylab("runs per game (combined for both teams") + xlab("season") + ggtitle("Evaluating Rockies' performance at Home field vs. Other fields ")


#Comparing the visualizations:
#I think the first visualization does a good job at conveying the difference in performance 
#at Home field vs other ballparks
#But the Boxplots give more insight bc they allow us to compare how big the difference is
#Also, Boxplots show us the outliers which is helpful. 


#What other questions can I ask? hmm... 

library(sqldf)
library(dplyr)

avgatt
tbl(avgatt, sql('SELECT Date, parkID, visitingteam, hometeam, VisitorRunsScored as AWR, HomeRunsScore as HRS'))



